-- 02_create_tables.sql
-- Creates synthetic canonical table names. Most are template-shaped; dashboard-critical tables are explicit.

USE DATABASE PEDIATRIC_AHA_DEMO;

CREATE OR REPLACE TABLE RAW_SYNTH.DIM_GENERIC_TEMPLATE (
  surrogate_id STRING,
  display_name STRING,
  category STRING,
  synthetic_demo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_SYNTH.FACT_GENERIC_TEMPLATE (
  fact_id STRING,
  site_id STRING,
  event_ts TIMESTAMP_NTZ,
  service_line STRING,
  synthetic_count NUMBER,
  synthetic_rate FLOAT,
  data_quality_flag STRING,
  synthetic_demo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_SYNTH.DIM_DATE (
  date_id STRING,
  date_value DATE,
  week_start_date DATE,
  month NUMBER,
  day_of_week STRING,
  is_weekend BOOLEAN,
  synthetic_school_day BOOLEAN
);

CREATE OR REPLACE TABLE RAW_SYNTH.DIM_TIME_BLOCK (
  time_block_id STRING,
  hour NUMBER,
  time_block_label STRING,
  shift STRING
);

CREATE OR REPLACE TABLE RAW_SYNTH.DIM_SITE (
  site_id STRING,
  site_name STRING,
  zone_name STRING,
  latitude FLOAT,
  longitude FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.DIM_UNIT (
  unit_id STRING,
  site_id STRING,
  unit_name STRING,
  service_line STRING,
  physical_beds NUMBER,
  baseline_occupancy FLOAT,
  is_high_resource BOOLEAN,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.DIM_BED (
  bed_id STRING,
  unit_id STRING,
  site_id STRING,
  is_isolation_capable BOOLEAN,
  is_monitored BOOLEAN,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_BED_CENSUS_HOURLY (
  census_hour_id STRING,
  site_id STRING,
  unit_id STRING,
  service_line STRING,
  ts_hour TIMESTAMP_NTZ,
  census NUMBER,
  physical_beds NUMBER,
  staffed_beds NUMBER,
  effective_beds NUMBER,
  occupancy_pct FLOAT,
  respiratory_multiplier FLOAT,
  ed_boarders NUMBER,
  predicted_discharges NUMBER,
  discharge_confidence FLOAT,
  staffing_gap_pct FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_BED_STATUS_HOURLY (
  bed_status_hour_id STRING,
  site_id STRING,
  unit_id STRING,
  ts_hour TIMESTAMP_NTZ,
  clean_beds NUMBER,
  beds_cleaning NUMBER,
  isolation_blocked_beds NUMBER,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_OCCUPANCY_SNAPSHOT (
  occupancy_snapshot_id STRING,
  site_id STRING,
  snapshot_ts TIMESTAMP_NTZ,
  census NUMBER,
  physical_beds NUMBER,
  staffed_beds NUMBER,
  effective_beds NUMBER,
  occupancy_pct FLOAT,
  ed_boarders NUMBER,
  predicted_discharges NUMBER,
  discharge_confidence FLOAT,
  staffing_gap_pct FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_WAITLIST_SNAPSHOT (
  waitlist_snapshot_id STRING,
  site_id STRING,
  program STRING,
  week_start_date DATE,
  waitlist_total NUMBER,
  waitlist_over_target NUMBER,
  median_wait_days NUMBER,
  p90_wait_days NUMBER,
  third_next_available_days NUMBER,
  urgent_breach_risk FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_REFERRAL (
  referral_id STRING,
  site_id STRING,
  program STRING,
  week_start_date DATE,
  new_referrals NUMBER,
  urgent_referrals NUMBER,
  triage_turnaround_median_days FLOAT,
  referral_completeness_pct FLOAT,
  duplicate_referral_count_synth NUMBER,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_CLINIC_SLOT (
  clinic_slot_id STRING,
  site_id STRING,
  program STRING,
  week_start_date DATE,
  slots_available NUMBER,
  slots_booked NUMBER,
  completed_visits NUMBER,
  no_show_rate FLOAT,
  late_cancel_rate FLOAT,
  virtual_share FLOAT,
  new_visit_share FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_DISCHARGE_BARRIER (
  discharge_barrier_id STRING,
  site_id STRING,
  barrier_type STRING,
  active_count NUMBER,
  median_age_hours FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_MODEL_PREDICTION_INPATIENT (
  model_prediction_id STRING,
  site_id STRING,
  model_id STRING,
  prediction_horizon_hours NUMBER,
  metric_name STRING,
  prediction FLOAT,
  p10 FLOAT,
  p90 FLOAT,
  top_driver_1 STRING,
  top_driver_2 STRING,
  top_driver_3 STRING,
  validation_status STRING,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_MODEL_PREDICTION_AMBULATORY (
  model_prediction_id STRING,
  site_id STRING,
  program STRING,
  model_id STRING,
  prediction_horizon_weeks NUMBER,
  metric_name STRING,
  prediction NUMBER,
  p10 NUMBER,
  p90 NUMBER,
  top_driver_1 STRING,
  top_driver_2 STRING,
  top_driver_3 STRING,
  validation_status STRING,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_SIMULATION_RESULT_INPATIENT (
  simulation_result_id STRING,
  scenario_name STRING,
  boarder_hours_mean FLOAT,
  boarder_hours_p10 FLOAT,
  boarder_hours_p90 FLOAT,
  p95_occupancy_mean FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RAW_SYNTH.FCT_SIMULATION_RESULT_AMBULATORY (
  simulation_result_id STRING,
  scenario_name STRING,
  final_backlog NUMBER,
  clearance_week NUMBER,
  mean_utilization FLOAT,
  breach_probability_proxy FLOAT,
  synthetic_demo BOOLEAN DEFAULT TRUE
);

-- Required dimensions not expanded above.
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_ZONE_OR_REGION LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_SERVICE_LINE LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_SPECIALTY LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_PROVIDER_GROUP LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_CLINIC LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_CLINIC_TEMPLATE LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_DIAGNOSIS_GROUP LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_PROCEDURE_GROUP LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_ACUITY_LEVEL LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_AGE_BAND LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_EQUITY_GEO_PROXY LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_OPEN_DATA_SOURCE LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_SCENARIO LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_MODEL LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.DIM_METRIC LIKE RAW_SYNTH.DIM_GENERIC_TEMPLATE;

-- Required facts not expanded above.
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_ADT_EVENT LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_INPATIENT_ENCOUNTER LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_ED_TO_INPATIENT_FLOW LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_OR_CASE LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_PACU_AND_PROCEDURAL_RECOVERY LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_TRANSFER_REQUEST LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_DISCHARGE_READINESS LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_LENGTH_OF_STAY LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_STAFFING_ROSTER_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_STAFFING_GAP_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_WORKLOAD_ACUITY_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_LAB_ORDER_TURNAROUND_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_IMAGING_TURNAROUND_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_PHARMACY_DISCHARGE_MED_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_TRANSPORT_OR_PORTERING_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_SAFETY_SIGNAL_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_READMISSION_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_SIMULATION_RUN_INPATIENT LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_REFERRAL_TRIAGE LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_APPOINTMENT LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_CLINIC_TEMPLATE_CAPACITY LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_PROVIDER_AVAILABILITY_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_NO_SHOW_OR_LATE_CANCEL_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_OVERDUE_FOLLOWUP_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_DIAGNOSTIC_QUEUE_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_PROCEDURE_QUEUE_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_VIRTUAL_CARE_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_POST_DISCHARGE_FOLLOWUP_SYNTH LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_SIMULATION_RUN_AMBULATORY LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_RESPIRATORY_VIRUS_ACTIVITY_OPEN LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_WEATHER_AND_AIR_QUALITY_OPEN LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_POPULATION_BY_AGE_REGION_OPEN LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_SCHOOL_CALENDAR_OR_HOLIDAY_OPEN LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_COMMUNITY_DEMAND_PROXY_OPEN LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;
CREATE OR REPLACE TABLE RAW_SYNTH.FCT_PUBLIC_HEALTH_ALERT_OR_SEASONAL_EVENT_OPEN LIKE RAW_SYNTH.FACT_GENERIC_TEMPLATE;

CREATE OR REPLACE TABLE APP.SCENARIO_RUN_LOG (
  scenario_name STRING,
  additional_surge_beds STRING,
  discharge_support_pct STRING,
  added_sessions STRING,
  virtual_conversion_pct STRING,
  reminder_coverage_pct STRING,
  estimated_boarder_hour_delta STRING,
  estimated_backlog_delta STRING,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

