-- 04_create_curated_views.sql
-- Curated views are the future real-data contract boundary.

USE DATABASE PEDIATRIC_AHA_DEMO;

CREATE OR REPLACE VIEW CURATED.VW_BED_CENSUS_HOURLY AS
SELECT * FROM RAW_SYNTH.FCT_BED_CENSUS_HOURLY WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_OCCUPANCY_SNAPSHOT AS
SELECT * FROM RAW_SYNTH.FCT_OCCUPANCY_SNAPSHOT WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_DISCHARGE_BARRIER AS
SELECT * FROM RAW_SYNTH.FCT_DISCHARGE_BARRIER WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_WAITLIST_SNAPSHOT AS
SELECT * FROM RAW_SYNTH.FCT_WAITLIST_SNAPSHOT WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_REFERRAL AS
SELECT * FROM RAW_SYNTH.FCT_REFERRAL WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_CLINIC_SLOT AS
SELECT * FROM RAW_SYNTH.FCT_CLINIC_SLOT WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_MODEL_PREDICTION_INPATIENT AS
SELECT * FROM RAW_SYNTH.FCT_MODEL_PREDICTION_INPATIENT WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_SIMULATION_RESULT_INPATIENT AS
SELECT * FROM RAW_SYNTH.FCT_SIMULATION_RESULT_INPATIENT WHERE synthetic_demo = TRUE;

CREATE OR REPLACE VIEW CURATED.VW_SIMULATION_RESULT_AMBULATORY AS
SELECT * FROM RAW_SYNTH.FCT_SIMULATION_RESULT_AMBULATORY WHERE synthetic_demo = TRUE;

