-- v3 canonical read-only synthetic views.
USE DATABASE PEDIATRIC_AHA_DEMO;

CREATE OR REPLACE VIEW CANONICAL.VW_SYNTH_UNIT_CENSUS_HOURLY AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_SYNTH_UNIT_CENSUS_HOURLY';

CREATE OR REPLACE VIEW CANONICAL.VW_SYNTH_ED_VISITS AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_SYNTH_ED_VISITS';

CREATE OR REPLACE VIEW CANONICAL.VW_SYNTH_REFERRALS AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_SYNTH_REFERRALS';

CREATE OR REPLACE VIEW MODEL.VW_MODEL_PREDICTIONS AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_MODEL_PREDICTIONS';
