-- v3 canonical read-only synthetic views.
USE DATABASE PEDIATRIC_AHA_DEMO;

CREATE OR REPLACE VIEW CANONICAL.VW_SYNTH_UNIT_CENSUS_HOURLY AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_UNIT_CENSUS';

CREATE OR REPLACE VIEW CANONICAL.VW_SYNTH_ED_BOARDING AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_ED_BOARDING';

CREATE OR REPLACE VIEW CANONICAL.VW_SYNTH_REFERRAL AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_REFERRAL';

CREATE OR REPLACE VIEW MODEL.VW_SYNTH_MODEL_OUTPUT AS
SELECT * FROM RAW_SYNTH.V3_OPERATIONAL_SIGNAL WHERE source_id = 'SRC_MODEL_OUTPUT';
