-- v3 learning-system writeback tables. These are Snowflake-side operational intelligence logs only.
USE DATABASE PEDIATRIC_AHA_DEMO;

CREATE OR REPLACE TABLE APP.USER_ANNOTATION (
  event_id STRING,
  event_type STRING,
  created_at TIMESTAMP_NTZ,
  created_by STRING,
  app_area STRING,
  site_id STRING,
  unit_or_program STRING,
  related_ids STRING,
  related_metric_id STRING,
  related_model_id STRING,
  related_panel_id STRING,
  related_scenario_id STRING,
  status STRING,
  severity STRING,
  note STRING,
  payload_json VARIANT,
  synthetic_demo_flag BOOLEAN
);

CREATE OR REPLACE TABLE APP.SCENARIO_RUN_LOG LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.WARNING_ACKNOWLEDGEMENT LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.METRIC_ISSUE_FLAG LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.MODEL_REVIEW_NOTE LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.GOVERNANCE_DECISION LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.VALIDATION_REVIEW LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.PANEL_FEEDBACK LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.HUDDLE_REVIEW_EVENT LIKE APP.USER_ANNOTATION;
CREATE OR REPLACE TABLE APP.LEARNING_SYSTEM_OUTCOME_REVIEW LIKE APP.USER_ANNOTATION;

CREATE OR REPLACE VIEW APP.V3_LEARNING_SYSTEM_EVENT AS
SELECT *, 'APP.USER_ANNOTATION' AS writeback_table FROM APP.USER_ANNOTATION
UNION ALL SELECT *, 'APP.WARNING_ACKNOWLEDGEMENT' FROM APP.WARNING_ACKNOWLEDGEMENT
UNION ALL SELECT *, 'APP.METRIC_ISSUE_FLAG' FROM APP.METRIC_ISSUE_FLAG
UNION ALL SELECT *, 'APP.MODEL_REVIEW_NOTE' FROM APP.MODEL_REVIEW_NOTE
UNION ALL SELECT *, 'APP.GOVERNANCE_DECISION' FROM APP.GOVERNANCE_DECISION
UNION ALL SELECT *, 'APP.VALIDATION_REVIEW' FROM APP.VALIDATION_REVIEW
UNION ALL SELECT *, 'APP.PANEL_FEEDBACK' FROM APP.PANEL_FEEDBACK
UNION ALL SELECT *, 'APP.HUDDLE_REVIEW_EVENT' FROM APP.HUDDLE_REVIEW_EVENT
UNION ALL SELECT *, 'APP.LEARNING_SYSTEM_OUTCOME_REVIEW' FROM APP.LEARNING_SYSTEM_OUTCOME_REVIEW;
