-- 10_smoke_tests.sql
-- Smoke tests after running scripts 00-09.

USE DATABASE PEDIATRIC_AHA_DEMO;

SELECT 'DIM_SITE' AS object_name, COUNT(*) AS row_count FROM RAW_SYNTH.DIM_SITE
UNION ALL
SELECT 'DIM_UNIT', COUNT(*) FROM RAW_SYNTH.DIM_UNIT
UNION ALL
SELECT 'FCT_BED_CENSUS_HOURLY', COUNT(*) FROM RAW_SYNTH.FCT_BED_CENSUS_HOURLY
UNION ALL
SELECT 'FCT_OCCUPANCY_SNAPSHOT', COUNT(*) FROM RAW_SYNTH.FCT_OCCUPANCY_SNAPSHOT
UNION ALL
SELECT 'FCT_WAITLIST_SNAPSHOT', COUNT(*) FROM RAW_SYNTH.FCT_WAITLIST_SNAPSHOT
UNION ALL
SELECT 'MART_INPATIENT_MISSION_CONTROL', COUNT(*) FROM MART.MART_INPATIENT_MISSION_CONTROL
UNION ALL
SELECT 'MART_AMBULATORY_ACCESS_MISSION_CONTROL', COUNT(*) FROM MART.MART_AMBULATORY_ACCESS_MISSION_CONTROL;

SELECT * FROM MART.MART_DATA_QUALITY_STATUS;

SELECT * FROM MODEL.DIM_MODEL_REGISTRY;

